--ENTIDADE PESSOA
CREATE TABLE PESSOA(
    CPF VARCHAR(16),
    NOME VARCHAR(80) NOT NULL,
    IDADE NUMBER(3) NOT NULL,
    CONSTRAINT PK_PESSOA PRIMARY KEY (CPF)
);

--OUTRA TABELA PARA ATRIBUTO CONTATO(PESSOA)
CREATE TABLE CONTATO_PESSOA(
    CPF VARCHAR(16),
    CONTATO NUMBER(10),
    CONSTRAINT FK_CONT_PESS FOREIGN KEY (CPF) REFERENCES PESSOA(CPF),
    CONSTRAINT PK_CONT_PESS PRIMARY KEY (CPF,CONTATO)
); 

--HERANCA COMPRADOR
CREATE TABLE COMPRADOR(
    CPF VARCHAR(16),
    CONSTRAINT FK_COMPR FOREIGN KEY (CPF) REFERENCES PESSOA(CPF),
    CONSTRAINT PK_COMPR PRIMARY KEY (CPF)
); 

--HERANCA VENDEDOR
CREATE TABLE VENDEDOR(
    CPF VARCHAR(16),
    NUM_VENDAS NUMBER(4) DEFAULT 0,
    CONSTRAINT FK_VEND FOREIGN KEY (CPF) REFERENCES PESSOA(CPF),
    CONSTRAINT PK_VEND PRIMARY KEY (CPF)
); 

--ENTIDADE DE NOME_CARTA
CREATE TABLE NOME_CARTA(
    VERSAO_CARTA VARCHAR(12),
    NOME VARCHAR(80) NOT NULL,
    CONSTRAINT FK_NOME_CARTA PRIMARY KEY (VERSAO_CARTA) 
);

--ENTIDADE CARTA
CREATE TABLE CARTA(
    CPF_PESSOA VARCHAR(16),
    VERSAO VARCHAR (12),
    PRECO NUMBER(20),
    QTD NUMBER (5) DEFAULT 1,
    CONSTRAINT FK_CARTA_CPF FOREIGN KEY (CPF_PESSOA) REFERENCES PESSOA(CPF),
    CONSTRAINT FK_CARTA_VERSAO FOREIGN KEY (VERSAO) REFERENCES NOME_CARTA(VERSAO_CARTA),
    CONSTRAINT PK_CARTA PRIMARY KEY (CPF_PESSOA, VERSAO)
);

--ENTIDADE DE PROMOCAO
CREATE TABLE PROMOCAO(
    CODIGO VARCHAR(8),
    DESCRICAO VARCHAR(200) NOT NULL,
    CONSTRAINT FK_PROMO PRIMARY KEY (CODIGO) 
);

--RELACAO MARCA DUELO
CREATE TABLE MARCA_DUELO(
    DESAFIANTE VARCHAR(16),
    DESAFIADO VARCHAR(16),
    DATA_DIA NUMBER(5),
    DATA_HORA NUMBER(5),
    DATA_MES NUMBER(5),
    DATA_ANO NUMBER(8),
    PREMIO VARCHAR(70),
    CONSTRAINT FK_MARC_DUEL_DESAFIANTE FOREIGN KEY (DESAFIANTE) REFERENCES PESSOA(CPF),
    CONSTRAINT FK_MARC_DUEL_DESAFIADO FOREIGN KEY (DESAFIADO) REFERENCES PESSOA(CPF), 
    CONSTRAINT PK_MARC_DUEL PRIMARY KEY(DESAFIANTE, DESAFIADO, DATA_DIA, DATA_HORA, DATA_MES, DATA_ANO)
);

--ENTIDADE ASSOCIATIVA TRANSACAO
CREATE TABLE TRANSACAO(
    COMPRADOR VARCHAR(16),
    VENDEDOR VARCHAR(16),
    VERSAO VARCHAR (12),
    DATA_TRANSACAO TIMESTAMP,
    CODIGO VARCHAR(4),
    QUANTIDADE NUMBER(10) CHECK (QUANTIDADE > 0),
    CONSTRAINT FK_TRAN_COMPRADOR FOREIGN KEY (COMPRADOR) REFERENCES PESSOA(CPF),
    CONSTRAINT FK_TRAN_CARTA FOREIGN KEY (VENDEDOR, VERSAO) REFERENCES CARTA(CPF_PESSOA, VERSAO),
    CONSTRAINT FK_TRAN_PROMO FOREIGN KEY (CODIGO) REFERENCES PROMOCAO(CODIGO),
    CONSTRAINT PK_TRAN PRIMARY KEY (COMPRADOR, VENDEDOR, VERSAO, DATA_TRANSACAO)
);



