--PROJECAO
SELECT * FROM PESSOA ORDER BY NOME;
SELECT * FROM PESSOA ORDER BY NOME DESC;

SELECT * FROM PESSOA P FULL OUTER JOIN CARTA C ON P.CPF = C.CPF_PESSOA;
SELECT * FROM PESSOA P FULL OUTER JOIN CARTA C ON P.CPF = C.CPF_PESSOA ORDER BY P.NOME;

/*
OI
:3
*/
SELECT P.NOME, COUNT(C.CPF_PESSOA)
FROM CARTA C FULL OUTER JOIN PESSOA P ON P.CPF = C.CPF_PESSOA
GROUP BY P.NOME; 

--DALE

SELECT P.NOME AS "NOME DO VENDEDOR", COUNT(C.CPF_PESSOA) AS "CARTAS DIFERENTES CADASTRADAS"
FROM CARTA C INNER JOIN PESSOA P ON P.CPF = C.CPF_PESSOA
GROUP BY P.NOME
HAVING COUNT(C.CPF_PESSOA) >1; 



--DOIDEIRA

SELECT P.NOME AS "NOME DO VENDEDOR", COUNT(C.CPF_PESSOA) AS "CARTAS DIFERENTES CADASTRADAS"
FROM CARTA C INNER JOIN PESSOA P ON P.CPF = C.CPF_PESSOA
WHERE P.NOME LIKE 'L%' OR P.NOME LIKE 'M%'
GROUP BY P.NOME
HAVING COUNT(C.CPF_PESSOA) >1; 

--TRANSACAO
INSERT INTO COMPRADOR VALUES('000.000.000-00');
INSERT INTO VENDEDOR (CPF) VALUES ('703.705.254-00');

INSERT INTO TRANSACAO (COMPRADOR, VENDEDOR, VERSAO, DATA_TRANSACAO,QUANTIDADE) 
VALUES('000.000.000-00','703.705.254-00','BLHR-EN061', current_date, 1);
SELECT * FROM TRANSACAO;
INSERT INTO TRANSACAO (COMPRADOR, VENDEDOR, VERSAO, DATA_TRANSACAO, QUANTIDADE) 
VALUES('000.000.000-00','703.705.254-00','BLHR-EN061', sysdate,2);
SELECT * FROM TRANSACAO;
INSERT INTO TRANSACAO (COMPRADOR, VENDEDOR, VERSAO, DATA_TRANSACAO, QUANTIDADE) 
VALUES('000.000.000-00','703.705.254-00','BLHR-EN061', sysdate-3,2);
SELECT * FROM TRANSACAO;