--Gabriel Ferreira Rocha
--group by, having e junção interna
SELECT P.NOME AS "NOME DO VENDEDOR", COUNT(C.CPF_PESSOA) AS "CARTAS DIFERENTES CADASTRADAS"
FROM CARTA C INNER JOIN PESSOA P ON P.CPF = C.CPF_PESSOA
WHERE P.NOME LIKE 'L%' OR P.NOME LIKE 'M%'
GROUP BY P.NOME
HAVING COUNT(C.CPF_PESSOA) >1; 

--Juncao externa
SELECT P.DESCRICAO, COUNT(T.CODIGO) AS APLICACOES 
FROM PROMOCAO P LEFT OUTER JOIN TRANSACAO T
ON P.CODIGO = T.CODIGO
GROUP BY P.DESCRICAO;


--Jose Lucas da Costa Silva
--SEMI JOIN
SELECT P.NOME
FROM PESSOA P
WHERE EXISTS (
    SELECT *
    FROM CARTA C
    WHERE C.CPF_PESSOA = P.CPF AND VERSAO = 'TLM-EN035'
);

--ANTI JOIN
SELECT P.NOME
FROM PESSOA P
WHERE NOT EXISTS (
    SELECT *
    FROM CARTA C
    WHERE C.CPF_PESSOA = P.CPF AND VERSAO = 'YGLD-ENC28'
);


--Lucas dos Reis Silva
--SUBCONSULTA ESCALAR
SELECT P.NOME, C.VERSAO, C.PRECO, C.QTD
FROM CARTA C INNER JOIN PESSOA P
ON C.CPF_PESSOA = P.CPF
WHERE C.PRECO =(
    SELECT MIN(CC.PRECO)
    FROM CARTA CC
);

--SUBCONSULTA TABELA
SELECT UNIQUE P.NOME, M.DESAFIADO
FROM MARCA_DUELO M INNER JOIN PESSOA P
ON M.DESAFIADO = P.CPF
WHERE M.DESAFIADO IN (
    SELECT C.CPF_PESSOA
    FROM CARTA C 
    WHERE C.CPF_PESSOA = M.DESAFIADO AND C.VERSAO = 'SP15-EN038'
);


--Marcelo Victor Batista
--SUBCONSULTA LINHA
SELECT NOME 
FROM PESSOA P INNER JOIN CARTA C
ON P.CPF = C.CPF_PESSOA
WHERE (C.VERSAO, P.IDADE) =(
    SELECT CC.VERSAO, PP.IDADE
    FROM PESSOA PP INNER JOIN CARTA CC
    ON PP.CPF = CC.CPF_PESSOA
    WHERE PP.CPF = '111.111.111-11' AND CC.VERSAO = 'MACR-EN039'
);


--Operação de conjunto
SELECT P.NOME
FROM COMPRADOR C INNER JOIN PESSOA P
ON C.CPF = P.CPF
INTERSECT
SELECT PP.NOME 
FROM VENDEDOR V INNER JOIN PESSOA PP
ON V.CPF = PP.CPF;